### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by MaxDesiatov** [SvenTiigi/SwiftKit#3]
## SwiftKit Environment

- SwiftKit version: latest
- macOS version: none
- Xcode version: none
- Installed via (mint, brew): built locally

## What did you do?

Tried to build and run SwiftKit on Linux.

## What did you expect to happen?

For SwiftKit to generate a project has first-class support for Linux out of the box.

## What happened instead?

Generated projects don't support Linux. Provided .travis.yml only builds on Xcode 10.2 on macOS.

Hi @SvenTiigi, thanks for the great project. I try to support Linux from the start for my open-source Swift projects. Would it be hard to add Linux support to SwiftKit?

**Comment by SvenTiigi** [comment]
Hi @MaxDesiatov 

thanks for the appreciation and using SwiftKit 🙌

When you generate a Kit a `Package.swift` file will be automatically generated for you. Therefore, the generated Kit is Linux ready.

As the main focus is currently set on iOS, tvOS and watchOS the `Xcode10.2` image has been chosen for the `.travis.yml` file as only the macOS target can be tested on a Linux operating system.

If I understood you correctly you would like to see that the `.travis.yml` file or in general the CI-Service configuration files contains the configuration that the `macOS` target will also be tested on a Linux operating system? Is this correct?

**Comment by SvenTiigi** [comment]
Closing due inactivity. Feel free to re-open the issue at any time.

**Comment by MaxDesiatov** [comment]
Sorry for the delay @SvenTiigi, unfortunately I don't have permissions to reopen issues in this repository. 

What I would love to see is for .travis.yml to suport a build matrix with jobs for both macOS and Linux. I'm not sure why would anyone test a macOS target on Linux, though. What I meant is a parallel job that at least runs `swift test` in the root of the package on a Linux distribution that has the latest stable Swift installed.

**Comment by SvenTiigi** [comment]
Hey @MaxDesiatov 

so the `.travis.yml` should look like this one:

```yml
branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

language: swift

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode10.2

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)" ; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then fastlane ios tests ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then swift test ; fi

```

**Comment by MaxDesiatov** [comment]
Thank you! I assume that `swiftenv` installation might take a while in a CI run, especially on Travis, which is notouriously slow in general. Would it be possible to use the latest official Swift Docker image in this matrix? Is there any chance that this variety of .travis.yml is going to be included in the template of `SwiftKit`, at least as an option if not the default?

**Comment by SvenTiigi** [comment]
Sure `SwiftKit` could offer two variants of the `Travis CI` configuration file.

```bash
🛠  Which CI-Service should be used?
1) Travis CI - macOS only
2) Travis CI - macOS & Linux
3) GitLab
(Type in the number or leave this empty to use none of them)
>
```

Please correct me if there are any bugs inside the `.travis.yml` 😅
```yml
branches:
  only:
    - master
    - develop
    - /^hotfix.*$/
    - /^feature.*$/

notifications:
  email:
    on_success: change
    on_failure: always

language: swift

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      env: swift=5.0
    - os: osx
      osx_image: xcode10.2

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker pull swift:$swift;
    fi;

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      fastlane ios tests;
    fi;
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      docker run -v $(pwd):/package -w /package swift:$swift /bin/sh -c "swift test";
    fi;

```
